In [1]:
a=100
b=100
print(a+b)


200


In [2]:
import numpy as np


In [3]:
import numpy as np

# Create a 1D array (Vector)
vector = np.array([1, 2, 3, 4])
print("1D Array:", vector)

# Create a 2D array (Matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", matrix)


1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# Array filled with zeros (Shape: 2 rows, 3 columns)
zeros_arr = np.zeros((2, 3)) 

# Array filled with ones
ones_arr = np.ones((3, 3))   

# Array with a sequence of numbers from 0 to 9
range_arr = np.arange(10)    

print("Zeros:\n", zeros_arr)
print("Sequence:", range_arr)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Sequence: [0 1 2 3 4 5 6 7 8 9]


In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", arr1 + arr2)       # Output: [5, 7, 9]

# Element-wise multiplication
print("Multiplication:", arr1 * arr2) # Output: [4, 10, 18]

# Scalar operation (Multiply every element by 10)
print("Scalar Multi:", arr1 * 10)     # Output: [10, 20, 30]


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Scalar Multi: [10 20 30]


In [6]:
# A 1D array of 6 elements
original = np.array([1, 2, 3, 4, 5, 6])

# Reshape into a 2D matrix (2 rows, 3 columns)
reshaped = original.reshape(2, 3)

print("Reshaped Matrix:\n", reshaped)


Reshaped Matrix:
 [[1 2 3]
 [4 5 6]]


In [7]:
data = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(data))       # Output: 150
print("Mean:", np.mean(data))     # Output: 30.0
print("Max Value:", np.max(data)) # Output: 50


Sum: 150
Mean: 30.0
Max Value: 50
